language: php

branches:
  only:
    - master
    - develop

php:
  - 5.6
  - 7
  - 7.1

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - mkdir build
  - ./vendor/bin/phpcs --standard=PSR2 ./src ./tests -p
  - ./vendor/bin/phpunit -c tests/phpunit.xml --coverage-clover build/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml

sudo: false
